### ISSUE TITLE
某门课程实际未被选中却变为ignored tasks

### ISSUE THREAD

**Issue by ziyao848** [Mzhhh/PKUElective2021Spring#4]
某门课程实际未被选中却变为ignored tasks，显示该课程permission required，终止程序再启动后恢复为current tasks，该情况出现了两次。但此前曾使用该程序补选成功过一门课，并未发生上述情况，2020版的程序也未出现过。

**Comment by Mzhhh** [comment]
我这版本没有改动判断是否ignore的逻辑，估计是网站本身的改动导致的。（当然另一个可能引起permission error的操作是的在跨院系开放之前试图跨院系选课）。您方便提供一下log文件发生错误的相应部分吗？

**Comment by zhongxinghong** [comment]
permission required 对应 ElectionPermissionError，它对应的错误信息是 "该课程在补退选阶段开始后的约一周开放选课" 但是具体什么原因有点忘了...... 总之就是，提交一次选课结果后如果被选课网明确的原因拒绝，那么这门课就会被忽略，以避免一直提交无效的选课请求

**Comment by Mzhhh** [comment]
> permission required 对应 ElectionPermissionError，它对应的错误信息是 "该课程在补退选阶段开始后的约一周开放选课" 但是具体什么原因有点忘了...... 总之就是，提交一次选课结果后如果被选课网明确的原因拒绝，那么这门课就会被忽略，以避免一直提交无效的选课请求



> permission required 对应 ElectionPermissionError，它对应的错误信息是 "该课程在补退选阶段开始后的约一周开放选课" 但是具体什么原因有点忘了...... 总之就是，提交一次选课结果后如果被选课网明确的原因拒绝，那么这门课就会被忽略，以避免一直提交无效的选课请求

这个提示对应的应该就是跨院系开放之前试图跨院系选课
