### ISSUE TITLE
有一门课程确定课程名、班号、开科单位无误，也在培养计划，但是提示not in your course plan, please check your config.

### ISSUE THREAD

**Issue by yingno** [Mzhhh/PKUElective2021Spring#5]

**Comment by yingno** [comment]
[course:pingpang]

name = 乒乓球（提高班）
class = 2
school = 体育教研部

**Comment by zhongxinghong** [comment]
这门课在补退选页的第几页？

**Comment by yingno** [comment]
> 这门课在补退选页的第几页？

第二页

**Comment by Mzhhh** [comment]
> > 这门课在补退选页的第几页？
> 
> 第二页

建议您检查一下 config.ini 中的 supply_cancel_page 是否正确设置为 2；并确保您在自己的浏览器打开补退选页面时，每一页显示的课程数量为 20
