### ISSUE TITLE
python main.py 报错

### ISSUE THREAD

**Issue by adavasa** [Mzhhh/PKUElective2021Spring#6]
class Environ(object, metaclass=Singleton):
                                   ^
SyntaxError: invalid syntax

不敢自己乱改代码。。。

**Comment by adavasa** [comment]
from .environ import Environ
  File "/Users/apple/Desktop/projects/source-1/9139726acb0c1de895c310accb463c0b_1615373530/autoelective/environ.py", line 10
    class Environ(object, metaclass=Singleton):
                                   ^
SyntaxError: invalid syntax

**Comment by Mzhhh** [comment]
这个估计是因为您不小心修改了文件，请重新 clone 一份试试
