### ISSUE TITLE
Unable to parse HTML content

### ISSUE THREAD

**Issue by Swhuagger** [Mzhhh/PKUElective2021Spring#7]
编程0基础，具体问题如下：
[ERROR] loop.error, 23:48:57, [104] unable to parse HTML content [WARNING] loop, 23:48:57, UnexceptedHTMLFormat encountered

**Comment by Mzhhh** [comment]
这个问题与原 repo 下的 [issue#56](https://github.com/zhongxinghong/PKUAutoElective/issues/56) 应该是一样的，我本人没有遇到过。根据原作者的分析：

> 现在报这个错误是因为选课网改了 HTML 的结构，导致会话超时的错误没有被正确捕获

建议您尝试将 config.ini 中的 elective_client_max_life 调小一点（如设为 200），预计下一次 commit 时会修改这个问题。

**Comment by Swhuagger** [comment]
已经尝试把 elective_client_max_life 调到200， 依然出现通用的现象。同时发现这问题只有在想选的课在第一页的时候才会出现

**Comment by Mzhhh** [comment]
> 已经尝试把 elective_client_max_life 调到200， 依然出现通用的现象。同时发现这问题只有在想选的课在第一页的时候才会出现

您现在用的是最新 commit 的版本吗？我在最新版本已经将按照原 repo 的 issue 下的方案进行了修改，如果最新版本还出现这个问题，麻烦您提供一下 log/web/ 下最新的一份 html。

**Comment by Swhuagger** [comment]
嗯嗯，最新版本没有问题了~
