### ISSUE TITLE
使用一段时间后将无法登陆选课网

### ISSUE THREAD

**Issue by autoelectiveuser** [Mzhhh/PKUElective2021Spring#8]
在使用刷课机一段时间后会报错如下： 
HTTPSConnectionPool(host='elective.pku.edu.cn', port=443): Max retries exceeded with url: /elective2008/ssoLogin.do?_rand=0.37325861354437806&token=13ebefa7a7ff3e73b0deef964739be80 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))
[WARNING] loop, 12:46:21, RequestException encountered
且人工手动登陆选课网也无法成功，即“当前无法使用此页面elective.pku.edu.cn 未发送任何数据。”

**Comment by Mzhhh** [comment]
应该是因为您的刷新频率太快了，导致 ip 被选课网暂时 ban 了（大概持续 1 小时）。您在这段时间内可以连接 vpn 后重新使用。建议您增加 refresh_interval 的值或增加 elective_client_pool_size。
