### ISSUE TITLE
出现如下错误可能的原因是什么？

### ISSUE THREAD

**Issue by autoelectiveuser** [Mzhhh/PKUElective2021Spring#9]
[ERROR] loop.error, 15:18:58, [103] unable to get normal Supplement page 3
[WARNING] loop, 15:18:58, OperationFailedError encountered

**Comment by Mzhhh** [comment]
根据原作者的 comment：
> 刷新非第一页的课程，第一次请求会遇到返回空页面的情况

个人认为是教学网本身的问题。

之前的版本中，出现三次返回空页面的情况下会抛出 OperationFailedError。但现在已经对这个问题进行了简单的处理，程序并不抛出 OperationFailedError，而是令出现此问题的 elective client 重新登录，应该可以解决，请您更新到最新版本后使用。
